-- Autogenerated: do not edit this file
select * from batch_job_instance where 1=1;
select * from batch_job_execution where 1=1;
select * from batch_job_execution_context where 1=1;
select * from batch_job_execution_params where 1=1;
select * from batch_step_execution where 1=1;
select * from batch_step_execution_context where 1=1;