spring:
  datasource:
    url: jdbc:postgresql://vault.anmani.link:5430/springbatchdb
    username: springbatchuser
    password: springbatchpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
