spring:
  datasource:
    url: jdbc:h2:file:./h2/test_data;AUTO_SERVER=TRUE
    username: testuser
    password: test1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2/test_data