spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/herdinbatch
    username: herdin
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2/test_data
  batch:
    initialize-schema: always